#define TITLE_TEXT "METOD"
#define SCREEN_RESOLUTION_W 800
#define SCREEN_RESOLUTION_H 600
#define SURFACE_TYPE SDL_HWSURFACE //SDL_SWSURFACE
#define TRANSPARENT_RGBA 0xffffff00
#define OPAQUE_RGBA 0x000000ff
#define RGBA_MAX_CH 0xff
#define MAX_LINE 255
#define COLOR_BLANK 0xffffffff

#define TITLE_POSX 230
#define TITLE_POSY 50
#define TITLE_WIDTH 150
#define TITLE_HEIGHT 55
#define TITLE_BG_COLOR 0x075f07bc
#define TITLE_TEXT_POSX 35
#define TITLE_TEXT_POSY 15
#define MENU_BG_COLOR 0x075f07bc
#define BORDER_MENU_COLOR 0xffffffff
#define MENU_SELECT_COLOR 0x7834b7ff
#define MENU_POSX 50
#define MENU_POSY 130
#define MENU_WIDTH 550
#define MENU_HEIGHT 250
#define BORDER_MENU_WIDTH 2
#define BORDER_MENU_COLOR 0xffffffff
#define MENU_CHOOSE_LEVEL_TXT "Choose level:"
#define MENU_TXT_POSX 25
#define MENU_TXT_POSY 15
#define MENU_EXIT_TXT "Exit"
#define MENU_EXIT_POSX (MENU_TXT_POSX)
#define MENU_EXIT_POSY (MENU_HEIGHT - 50)


